package potato.spark

import potato.common.conf.POTATO_PREFIX

package object conf {
  val POTATO_APP_NAME_KEY = "spark.app.name"
  val POTATO_MAIN_CLASS: String = POTATO_PREFIX + "main.class"
  val POTATO_SPARK_PREFIX: String = POTATO_PREFIX + "spark."
  // spark streaming 批次间隔key。
  val POTATO_SPARK_STREAMING_BATCH_DURATION_MS_KEY: String = POTATO_SPARK_PREFIX + "streaming.batch.duration.ms"
  val POTATO_SPARK_ADDITIONAL_SERVICES_KEY: String = POTATO_SPARK_PREFIX + "additional.services"
  val POTATO_SPARK_CUSTOM_SERVICES_CLASS_KEY: String = POTATO_SPARK_PREFIX + "custom.services.class"

  val POTATO_LOCK_SINGLETON_PREFIX: String = POTATO_PREFIX + "lock.singleton."

  val POTATO_LOCK_SINGLETON_TRY_MAX_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "try.max"
  val POTATO_LOCK_SINGLETON_TRY_MAX_DEFAULT: String = 3.toString
  val POTATO_LOCK_SINGLETON_TRY_INTERVAL_MS_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "try.interval.ms"
  val POTATO_LOCK_SINGLETON_TRY_INTERVAL_MS_DEFAULT: String = 30000.toString
  val POTATO_LOCK_SINGLETON_FORCE_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "force"
  val POTATO_LOCK_SINGLETON_FORCE_DEFAULT: String = false.toString
  val POTATO_LOCK_SINGLETON_TYPE_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "type"
  val POTATO_LOCK_SINGLETON_TYPE_DEFAULT: String = "zookeeper"

  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX: String = POTATO_LOCK_SINGLETON_PREFIX + "zookeeper."
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_QUORUM_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "quorum"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_TIMEOUT_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "timeout"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_TIMEOUT_DEFAULT: String = 60000.toString
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PATH_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "path"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PATH_DEFAULT: String = "/potato/spark/lock/singleton"
}
