package spark.potato.monitor.conf

import spark.potato.common.conf.CommonConfigKeys.POTATO_PREFIX

object MonitorConfigKeys {
  val POTATO_MONITOR_PREFIX: String = POTATO_PREFIX + "monitor."

  val POTATO_MONITOR_BACKLOG_PREFIX: String = POTATO_MONITOR_PREFIX + "backlog."
  val POTATO_MONITOR_BACKLOG_ENABLE_KEY: String = POTATO_MONITOR_BACKLOG_PREFIX + "enable"
  val POTATO_MONITOR_BACKLOG_ENABLE_DEFAULT: Boolean = true
  val POTATO_MONITOR_BACKLOG_DELAY_SECONDS_KEY: String = POTATO_MONITOR_BACKLOG_PREFIX + "delay.sec"

  val POTATO_MONITOR_BACKLOG_REPORTER_PREFIX: String = POTATO_MONITOR_BACKLOG_PREFIX + "reporter."
  val POTATO_MONITOR_BACKLOG_REPORTER_INTERVAL_SECOND_KEY: String = POTATO_MONITOR_BACKLOG_REPORTER_PREFIX + "interval.sec"
  val POTATO_MONITOR_BACKLOG_REPORTER_INTERVAL_SECOND_DEFAULT: Int = 900
  val POTATO_MONITOR_BACKLOG_REPORTER_MAX_KEY: String = POTATO_MONITOR_BACKLOG_REPORTER_PREFIX + "max"
  val POTATO_MONITOR_BACKLOG_REPORTER_MAX_DEFAULT: Int = 3
  val POTATO_MONITOR_BACKLOG_REPORTER_TYPE_KEY: String = POTATO_MONITOR_BACKLOG_REPORTER_PREFIX + "type"

  val POTATO_MONITOR_BACKLOG_REPORTER_TYPE_DEFAULT: String = "ding"
  val POTATO_MONITOR_BACKLOG_REPORTER_DING_PREFIX: String = POTATO_MONITOR_BACKLOG_REPORTER_PREFIX + "ding."
  val POTATO_MONITOR_BACKLOG_REPORTER_DING_TOKEN_KEY: String = POTATO_MONITOR_BACKLOG_REPORTER_DING_PREFIX + "token"
  val POTATO_MONITOR_BACKLOG_REPORTER_DING_ATALL_KEY: String = POTATO_MONITOR_BACKLOG_REPORTER_DING_PREFIX + "atall"
  val POTATO_MONITOR_BACKLOG_REPORTER_DING_ATALL_DEFAULT: Boolean = false
  val POTATO_MONITOR_BACKLOG_REPORTER_DING_ATPHONEs_KEY: String = POTATO_MONITOR_BACKLOG_REPORTER_DING_PREFIX + "atphones"
  val POTATO_MONITOR_BACKLOG_REPORTER_DING_ATPHONEs_DEFAULT = Array.empty[String]
}
