package spark.streaming.potato.conf

object ConfigKeys {
  val POTATO_PREFIX = "spark.potato."
  val POTATO_STREAMING_SLIDE_DURATION_SECONDS_KEY: String = POTATO_PREFIX + "streaming.slide.duration.seconds"
  val POTATO_STREAMING_SLIDE_DURATION_SECONDS_DEFAULT = 60L

  val POTATO_SOURCE_PREFIX = "spark.potato.source"
  val POTATO_SOURCE_KAFKA_PREFIX: String = POTATO_SOURCE_PREFIX + "kafka."
  val POTATO_SOURCE_KAFKA_TOPICS_KEY: String = POTATO_SOURCE_KAFKA_PREFIX + "topics"
  val POTATO_SOURCE_KAFKA_CONSUMER_PARAMS_PREFIX: String = POTATO_SOURCE_KAFKA_PREFIX + "consumer."
  val POTATO_SOURCE_KAFKA_GROUP_KEY: String = POTATO_SOURCE_KAFKA_CONSUMER_PARAMS_PREFIX + "group.id"
}
