package spark.potato.lock

import spark.potato.common.conf.POTATO_PREFIX

package object conf {
  val POTATO_LOCK_SINGLETON_PREFIX: String = POTATO_PREFIX + "lock.singleton."

  val POTATO_LOCK_SINGLETON_TRY_MAX_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "try.max"
  val POTATO_LOCK_SINGLETON_TRY_MAX_DEFAULT: String = 3.toString
  val POTATO_LOCK_SINGLETON_TRY_INTERVAL_MS_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "try.interval.ms"
  val POTATO_LOCK_SINGLETON_TRY_INTERVAL_MS_DEFAULT: String = 30000.toString
  val POTATO_LOCK_SINGLETON_FORCE_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "force"
  val POTATO_LOCK_SINGLETON_FORCE_DEFAULT: String = false.toString
  val POTATO_LOCK_SINGLETON_TYPE_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "type"
  val POTATO_LOCK_SINGLETON_TYPE_DEFAULT: String = "zookeeper"

  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX: String = POTATO_LOCK_SINGLETON_PREFIX + "zookeeper."
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_QUORUM_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "quorum"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_TIMEOUT_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "timeout"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_TIMEOUT_DEFAULT: String = 60000.toString
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PATH_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "path"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PATH_DEFAULT: String = "/potato/lock/singletonLock"

  val POTATO_LOCK_SINGLETON_CONTEXT_SERVICE_NAME: String = "ContextSingletonLock"
  val POTATO_LOCK_SINGLETON_STREAMING_SERVICE_NAME: String = "StreamingSingletonLock"
}
