package spark.potato.lock

import spark.potato.common.conf.POTATO_PREFIX

package object conf {
  val POTATO_LOCK_SINGLETON_PREFIX: String = POTATO_PREFIX + "lock.singleton."

  val POTATO_LOCK_SINGLETON_TRY_MAX_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "try.max"
  val POTATO_LOCK_SINGLETON_TRY_MAX_DEFAULT: Int = 3
  val POTATO_LOCK_SINGLETON_TRY_INTERVAL_MS_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "try.interval.ms"
  val POTATO_LOCK_SINGLETON_TRY_INTERVAL_MS_DEFAULT: Int = 30000
  val POTATO_LOCK_SINGLETON_FORCE_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "force"
  val POTATO_LOCK_SINGLETON_FORCE_DEFAULT: Boolean = false
  val POTATO_LOCK_SINGLETON_HEARTBEAT_INTERVAL_MS_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "heartbeat.interval.ms"
  val POTATO_LOCK_SINGLETON_HEARTBEAT_INTERVAL_MS_DEFAULT: Int = 10000
  val POTATO_LOCK_SINGLETON_HEARTBEAT_TIMEOUT_MS_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "heartbeat.timeout.ms"
  val POTATO_LOCK_SINGLETON_HEARTBEAT_TIMEOUT_MS_DEFAULT: Int = 90000
  val POTATO_LOCK_SINGLETON_TYPE_KEY: String = POTATO_LOCK_SINGLETON_PREFIX + "type"
  val POTATO_LOCK_SINGLETON_TYPE_DEFAULT: String = "zookeeper"

  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX: String = POTATO_LOCK_SINGLETON_PREFIX + "zookeeper."
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_QUORUM_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "quorum"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PATH_KEY: String = POTATO_LOCK_SINGLETON_ZOOKEEPER_PREFIX + "path"
  val POTATO_LOCK_SINGLETON_ZOOKEEPER_PATH_DEFAULT: String = "/potato/lock/singletonLock"

  val POTATO_LOCK_SINGLETON_CONTEXT_SERVICE_NAME: String = "ContextSingletonLock"
  val POTATO_LOCK_SINGLETON_STREAMING_SERVICE_NAME: String = "StreamingSingletonLock"
}
