package spark.potato.monitor

import spark.potato.common.conf.CommonConfigKeys

object MonitorConfigKeys {
  val MONITOR_PREFIX: String = CommonConfigKeys.POTATO_PREFIX + "monitor."

  val MONITOR_BACKLOG_PREFIX: String = MONITOR_PREFIX + "backlog."
  val MONITOR_BACKLOG_ENABLE_KEY: String = MONITOR_BACKLOG_PREFIX + "enable"
  val MONITOR_BACKLOG_ENABLE_DEFAULT: Boolean = true
  val MONITOR_BACKLOG_DELAY_SECONDS_KEY: String = MONITOR_BACKLOG_PREFIX + "delay.sec"

  val MONITOR_BACKLOG_REPORTER_PREFIX: String = MONITOR_BACKLOG_PREFIX + "reporter."
  val BACKLOG_REPORTER_INTERVAL_SECOND_KEY: String = MONITOR_BACKLOG_REPORTER_PREFIX + "interval.sec"
  val BACKLOG_REPORTER_INTERVAL_SECOND_DEFAULT: Int = 900
  val BACKLOG_REPORTER_MAX_KEY: String = MONITOR_BACKLOG_REPORTER_PREFIX + "max"
  val BACKLOG_REPORTER_MAX_DEFAULT: Int = 3
  val BACKLOG_REPORTER_TYPE_KEY: String = MONITOR_BACKLOG_REPORTER_PREFIX + "type"

  val BACKLOG_REPORTER_TYPE_DEFAULT: String = "ding"
  val BACKLOG_REPORTER_DING_PREFIX: String = MONITOR_BACKLOG_REPORTER_PREFIX + "ding."
  val BACKLOG_REPORTER_DING_TOKEN_KEY: String = BACKLOG_REPORTER_DING_PREFIX + "token"
  val BACKLOG_REPORTER_DING_ATALL_KEY: String = BACKLOG_REPORTER_DING_PREFIX + "atall"
  val BACKLOG_REPORTER_DING_ATALL_DEFAULT: Boolean = false
  val BACKLOG_REPORTER_DING_ATPHONEs_KEY: String = BACKLOG_REPORTER_DING_PREFIX + "atphones"
  val BACKLOG_REPORTER_DING_ATPHONEs_DEFAULT = Array.empty[String]
}
